# Generated by Django 5.1.2 on 2024-11-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.IntegerField(null=True)),
                ('business_name', models.TextField(null=True)),
                ('type', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('social_media', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
            ],
        ),
    ]
