# Generated by Django 5.1.2 on 2024-12-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_business_instagram_business_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='ratings',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
